// ============================================================
// scripture-cite — Enums
// Type-safe identifiers for all scripture references
// ============================================================

export enum ScriptureSource {
  BIBLE = "bible",
  QURAN = "quran",
  GITA = "gita",
}

export enum DisplayMode {
  INLINE = "inline",
  TOOLTIP = "tooltip",
}

// ── Bible Books (Old Testament + New Testament) ─────────────

export enum BibleBook {
  GENESIS = "genesis",
  EXODUS = "exodus",
  LEVITICUS = "leviticus",
  NUMBERS = "numbers",
  DEUTERONOMY = "deuteronomy",
  JOSHUA = "joshua",
  JUDGES = "judges",
  RUTH = "ruth",
  FIRST_SAMUEL = "1-samuel",
  SECOND_SAMUEL = "2-samuel",
  FIRST_KINGS = "1-kings",
  SECOND_KINGS = "2-kings",
  FIRST_CHRONICLES = "1-chronicles",
  SECOND_CHRONICLES = "2-chronicles",
  EZRA = "ezra",
  NEHEMIAH = "nehemiah",
  ESTHER = "esther",
  JOB = "job",
  PSALMS = "psalms",
  PROVERBS = "proverbs",
  ECCLESIASTES = "ecclesiastes",
  SONG_OF_SOLOMON = "song-of-solomon",
  ISAIAH = "isaiah",
  JEREMIAH = "jeremiah",
  LAMENTATIONS = "lamentations",
  EZEKIEL = "ezekiel",
  DANIEL = "daniel",
  HOSEA = "hosea",
  JOEL = "joel",
  AMOS = "amos",
  OBADIAH = "obadiah",
  JONAH = "jonah",
  MICAH = "micah",
  NAHUM = "nahum",
  HABAKKUK = "habakkuk",
  ZEPHANIAH = "zephaniah",
  HAGGAI = "haggai",
  ZECHARIAH = "zechariah",
  MALACHI = "malachi",
  MATTHEW = "matthew",
  MARK = "mark",
  LUKE = "luke",
  JOHN = "john",
  ACTS = "acts",
  ROMANS = "romans",
  FIRST_CORINTHIANS = "1-corinthians",
  SECOND_CORINTHIANS = "2-corinthians",
  GALATIANS = "galatians",
  EPHESIANS = "ephesians",
  PHILIPPIANS = "philippians",
  COLOSSIANS = "colossians",
  FIRST_THESSALONIANS = "1-thessalonians",
  SECOND_THESSALONIANS = "2-thessalonians",
  FIRST_TIMOTHY = "1-timothy",
  SECOND_TIMOTHY = "2-timothy",
  TITUS = "titus",
  PHILEMON = "philemon",
  HEBREWS = "hebrews",
  JAMES = "james",
  FIRST_PETER = "1-peter",
  SECOND_PETER = "2-peter",
  FIRST_JOHN = "1-john",
  SECOND_JOHN = "2-john",
  THIRD_JOHN = "3-john",
  JUDE = "jude",
  REVELATION = "revelation",
}

// ── Quran Surahs (all 114) ──────────────────────────────────

export enum QuranSurah {
  AL_FATIHA = "1",
  AL_BAQARAH = "2",
  AL_IMRAN = "3",
  AN_NISA = "4",
  AL_MAIDAH = "5",
  AL_ANAM = "6",
  AL_ARAF = "7",
  AL_ANFAL = "8",
  AT_TAWBAH = "9",
  YUNUS = "10",
  HUD = "11",
  YUSUF = "12",
  AR_RAD = "13",
  IBRAHIM = "14",
  AL_HIJR = "15",
  AN_NAHL = "16",
  AL_ISRA = "17",
  AL_KAHF = "18",
  MARYAM = "19",
  TA_HA = "20",
  AL_ANBIYA = "21",
  AL_HAJJ = "22",
  AL_MUMINUN = "23",
  AN_NUR = "24",
  AL_FURQAN = "25",
  ASH_SHUARA = "26",
  AN_NAML = "27",
  AL_QASAS = "28",
  AL_ANKABUT = "29",
  AR_RUM = "30",
  LUQMAN = "31",
  AS_SAJDAH = "32",
  AL_AHZAB = "33",
  SABA = "34",
  FATIR = "35",
  YA_SIN = "36",
  AS_SAFFAT = "37",
  SAD = "38",
  AZ_ZUMAR = "39",
  GHAFIR = "40",
  FUSSILAT = "41",
  ASH_SHURA = "42",
  AZ_ZUKHRUF = "43",
  AD_DUKHAN = "44",
  AL_JATHIYAH = "45",
  AL_AHQAF = "46",
  MUHAMMAD = "47",
  AL_FATH = "48",
  AL_HUJURAT = "49",
  QAF = "50",
  ADH_DHARIYAT = "51",
  AT_TUR = "52",
  AN_NAJM = "53",
  AL_QAMAR = "54",
  AR_RAHMAN = "55",
  AL_WAQIAH = "56",
  AL_HADID = "57",
  AL_MUJADILA = "58",
  AL_HASHR = "59",
  AL_MUMTAHANAH = "60",
  AS_SAFF = "61",
  AL_JUMUAH = "62",
  AL_MUNAFIQUN = "63",
  AT_TAGHABUN = "64",
  AT_TALAQ = "65",
  AT_TAHRIM = "66",
  AL_MULK = "67",
  AL_QALAM = "68",
  AL_HAQQAH = "69",
  AL_MAARIJ = "70",
  NUH = "71",
  AL_JINN = "72",
  AL_MUZZAMMIL = "73",
  AL_MUDDATHTHIR = "74",
  AL_QIYAMAH = "75",
  AL_INSAN = "76",
  AL_MURSALAT = "77",
  AN_NABA = "78",
  AN_NAZIAT = "79",
  ABASA = "80",
  AT_TAKWIR = "81",
  AL_INFITAR = "82",
  AL_MUTAFFIFIN = "83",
  AL_INSHIQAQ = "84",
  AL_BURUJ = "85",
  AT_TARIQ = "86",
  AL_ALA = "87",
  AL_GHASHIYAH = "88",
  AL_FAJR = "89",
  AL_BALAD = "90",
  ASH_SHAMS = "91",
  AL_LAYL = "92",
  AD_DUHA = "93",
  ASH_SHARH = "94",
  AT_TIN = "95",
  AL_ALAQ = "96",
  AL_QADR = "97",
  AL_BAYYINAH = "98",
  AZ_ZALZALAH = "99",
  AL_ADIYAT = "100",
  AL_QARIAH = "101",
  AT_TAKATHUR = "102",
  AL_ASR = "103",
  AL_HUMAZAH = "104",
  AL_FIL = "105",
  QURAYSH = "106",
  AL_MAUN = "107",
  AL_KAWTHAR = "108",
  AL_KAFIRUN = "109",
  AN_NASR = "110",
  AL_MASAD = "111",
  AL_IKHLAS = "112",
  AL_FALAQ = "113",
  AN_NAS = "114",
}

// ── Bhagavad Gita Chapters (all 18) ────────────────────────

export enum GitaChapter {
  CH_1 = "1",
  CH_2 = "2",
  CH_3 = "3",
  CH_4 = "4",
  CH_5 = "5",
  CH_6 = "6",
  CH_7 = "7",
  CH_8 = "8",
  CH_9 = "9",
  CH_10 = "10",
  CH_11 = "11",
  CH_12 = "12",
  CH_13 = "13",
  CH_14 = "14",
  CH_15 = "15",
  CH_16 = "16",
  CH_17 = "17",
  CH_18 = "18",
}

export type VerseNumber = `${number}`;
export type ChapterNumber = `${number}`;
